export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT'
export  const SET_INGREDIENTS='SET_INGREDIENTS'
export const SET_INGREDIENTS_FAILED='SET_INGREDIENTS_FAILED'

//order types
export const PURCHASE_LOADING='PURCHASE_LOADING'
export const ORDER_SUCCESS='ORDER_SUCCESS';
export const ORDER_FAIL='ORDER_FAIL'